server:
  port: 8084

spring:
  application:
    name: order-service

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

## configuration for our circuit breaker
resilience4j:
  retry:
    instances:
      warehouseServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      warehouseServiceCircuitBreaker:
        sliding-window-size: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

logging:
  level:
    io.github.resilience4j: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always